import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MedievalSharp } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const medievalSharp = MedievalSharp({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-medieval",
});

export const metadata: Metadata = {
  title: "Legionen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex items-center text-5xl justify-center bg-red-700 text-black hover:text-white duration-[500ms]">
          LEGIONEN
        </div>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger className="hover:bg-red-700 hover:text-white duration-[300ms] mt-2 ml-1" />
          <SidebarInset className="flex justify-center">
            {children}
          </SidebarInset>
        </SidebarProvider>
        
      </body>
    </html>
  );
}
