import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MedievalSharp } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const medievalSharp = MedievalSharp({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-medieval",
});

export const metadata: Metadata = {
  title: "Legionen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex items-center text-5xl justify-center bg-red-700 text-black hover:text-white duration-500 fixed w-full">
          LEGIONEN
        </div>
        <div className="flex min-h-screen w-full">
          <SidebarProvider className="w-auto flex-none">
            <AppSidebar />
            <SidebarTrigger className="mt-2.5 ml-2 duration-300 absolute! left-0 z-20 hover:cursor-pointer" />
          </SidebarProvider>
          <main className="flex min-h-screen items-center justify-center px-6 py-4 w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
